# codecov.yml (repo root)

codecov:
  # Only report coverage when CI itself has passed
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down

  status:
    project:
      default:
        # Overall repo coverage target (JaCoCo line coverage)
        target: 60%
        threshold: 2%   # small wiggle room so tiny drops don't fail CI

    patch:
      default:
        # New / changed lines should have *some* tests,
        # but don't make it too strict for coursework.
        target: 25%
        threshold: 2%

comment:
  # What Codecov posts on PRs
  layout: "reach, diff, flags, files, components"
  require_changes: true
