name: Feature request
description: Request a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature 🙌  
        Please fill in all sections so we can understand the value and implement it correctly.

  - type: input
    id: summary
    attributes:
      label: Short summary
      description: One sentence that describes the new feature.
      placeholder: "Example: R07 city report should filter by continent and country"
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected area / requirement
      description: Which part of the project does this feature relate to?
      options:
        - "R01–R06 – Country reports"
        - "R07–R16 – City reports"
        - "R17–R22 – Capital city reports"
        - "R23–R25 – Population in/out of cities"
        - "R26–R31 – Population totals lookups"
        - "R32 – Languages report"
        - "General DevOps / CI / Documentation"
    validations:
      required: true

  - type: input
    id: requirement_id
    attributes:
      label: Requirement ID (if applicable)
      description: "For example: R01, R15, R23. Leave blank for general improvements."
      placeholder: "R01"
    validations:
      required: false

  - type: textarea
    id: user_story
    attributes:
      label: User story
      description: "Use the format: As a <role>, I want <goal> so that <reason>."
      placeholder: |
        As a consumer of the API,
        I want to retrieve the top-N countries by population in a region,
        so that I can build regional dashboards.
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Description
      description: "Describe the feature in more detail. Include inputs, outputs, and any constraints."
      placeholder: |
        - New endpoint: GET /reports/countries/top/{n}
        - Optional filter: ?continent=Asia
        - Response fields: Code, Name, Continent, Region, Population, Capital
        - Must reuse existing WorldRepo queries where possible.
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
    description: "List clear, testable acceptance criteria using checkboxes."
      value: |
        - [ ] Given a valid continent and N, when I call the endpoint, then I get the top-N countries sorted by population DESC.
        - [ ] When no continent is provided, the endpoint returns the top-N countries in the world.
        - [ ] Response includes Code, Name, Continent, Region, Population, Capital for each country.
        - [ ] Automated tests cover typical, edge, and error cases.
      render: markdown
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent/impactful is this?
      options:
        - "P0 – Critical"
        - "P1 – High"
        - "P2 – Medium"
        - "P3 – Low"
    validations:
      required: true

  - type: checkboxes
    id: impact
    attributes:
      label: Impact and follow-up
      description: Check all that apply.
      options:
        - label: "Requires database/schema changes"
        - label: "Requires updates to existing tests or new tests"
        - label: "Requires documentation / README updates"
        - label: "Affects CI, Docker, or deployment configuration"
    validations:
      required: false

  - type: checkboxes
    id: dod
    attributes:
      label: Definition of Done (DoD)
      description: Ensure quality and evidence for assessment.
      options:
        - label: "Unit and integration tests added and passing in CI"
        - label: "Coverage threshold met; Codecov status green"
        - label: "README/Docs updated (workflow, badges, evidence)"
        - label: "Linked to requirement (R01–R32 if applicable) and Project board"
    validations:
      required: true
