name: Feature request
description: Request a feature
title: "[Feature]: "
labels: ["feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / value
      description: What outcome do you want and why?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      value: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: true
