@startuml
title Use Case Diagram2: Generate Cities Population Report

actor "City Planner" as Planner
actor "Project Owner" as Owner

rectangle "Population Analyst System" {

    usecase "Generate All Cities Population Report" as UC_Main

    usecase "View All Cities of World" as UC_World
    usecase "View All Cities by Continent" as UC_Continent
    usecase "View All Cities by Region" as UC_Region
    usecase "View All Cities by Country" as UC_Country
    usecase "View All Cities by District" as UC_District
}

Owner --> UC_Main
Planner --> UC_Main

UC_Main <|-- UC_World
UC_Main <|-- UC_Continent
UC_Main <|-- UC_Region
UC_Main <|-- UC_Country
UC_Main <|-- UC_District

note right of UC_Main
This is the main use case for generating
all selected cities population reports. Extensions and sub-variations are
for continent, region, country and district.
end note

@enduml
