# .github/workflows/auto-triage.yml
name: Auto-triage issues

on:
  issues:
    types: [opened, reopened]   # run when a new/ reopened issue appears

# Minimal permissions for this workflow
permissions:
  contents: read
  issues: write
  # Only needed if you UNCOMMENT the "Add to Project" step below:
  # repository-projects: write

concurrency:
  group: triage-${{ github.event.issue.number }}
  cancel-in-progress: false

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      # 1) Auto-label the issue
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: triage

      # 2) (Optional) Add the issue to a Classic Project
      # - uses: actions/add-to-project@v1
      #   with:
      #     project-url: https://github.com/orgs/<ORG>/projects/<ID>
      #     # Classic PAT with "repo" + "project" scopes
      #     github-token: ${{ secrets.CLASSIC_PROJECTS_TOKEN }}
